[package]
name = "trace"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.41"
aya = { version = "0.10.2", features = ["async_tokio"] }
bytes = "1.0.1"
futures = "0.3.15"
plain = "0.2.3"
structopt = "0.3.21"
tokio = "1.7.1"
